export const WS_MESSAGE_HANDLER_KEY = Symbol('WS_MESSAGE_HANDLER');
export const WS_CONNECTION_NAME = Symbol('WS_CONNECTION_NAME');
export const WS_CLIENT_PROVIDER_PREFIX = 'WS_CLIENT_PROVIDER';
export const WS_CLIENT_PROVIDER_TOKEN = 'WS_CLIENT_PROVIDER_TOKEN';
export const WS_CLIENT_INSTANCE_PROPERTY = 'WS_CLIENT_INSTANCE_PROPERTY';
